#!/usr/bin/env zsh

files=("misc.ml" "substitution.ml" "context.ml" "variance.ml" "printing.ml" "typer.ml")

OPTIND=1
warnings=()
nowarn=1
verb=0

# Prints help message
show_help () {
    echo "usage: ./stat.sh [-vf]"
    echo "  -h : show this help message"
    echo "  -w : show_warnings"
}

# Options parsing
while getopts "hw" opt; do
    case $opt in
        h)
            show_help
            exit 0
            ;;
        w)
            verb=1
            ;;
    esac
done

# For a pretty print
aligned_print () {
    n=$(echo $1 | wc -c)
    n=$((30 - n)) 
    if [ $2 -gt 1 ]; then
        plural="s"
    else
        plural=""
    fi
    printf "    $1%${n}s $2 occurence$plural\n" ":"
}

# Prints the list of useless functions
show_warns () {
    echo
    if [ $nowarn -eq 1 ]; then
        echo "Toutes les fonctions sont utilisées au moins une fois."
    else
        echo "Les fonctions ci-dessous ne sont jamais utilisées dans le programme :"
        for val in $warnings; do
            echo " - $val"
        done
    fi
}

# Counts the number of appearance of each function 
for f in $files; do
    echo "Fonctions du fichier $f :"
    liste=$(ocamlc -i $f | grep -o "^val [a-Z0-1_]\+" | sed "s/^val //")
    echo $liste | while read val; do
        nb=$(cat *.ml | grep -o "[^a-Z0-9_]${val}[ ()]" | wc -l)
        if [ $nb -eq 1 ]; then
            warnings+=$val
            nowarn=0
        fi
        aligned_print $val $nb
    done
    echo
done

if [ $verb -eq 1 ]; then
    show_warns
fi

